### Import Libraries

In [1]:
import pandas as pd
import numpy as np

### Load Dataset

In [2]:
df = pd.read_csv('data/raw/amazon (raw_data).csv')
df.head()

,product_id,product_name,category,discounted_price,actual_price,discount_percentage,rating,rating_count,about_product,user_id,user_name,review_id,review_title,review_content,img_link,product_link
0,B07JW9H4J1,Wayona Nylon Braided USB to Lightning Fast Cha...,Computers&Accessories|Accessories&Peripherals|...,₹399,"₹1,099",64%,4.2,"24,269",High Compatibility : Compatible With iPhone 12...,"AG3D6O4STAQKAY2UVGEUV46KN35Q,AHMY5CWJMMK5BJRBB...","Manav,Adarsh gupta,Sundeep,S.Sayeed Ahmed,jasp...","R3HXWT0LRP0NMF,R2AJM3LFTLZHFO,R6AQJGUP6P86,R1K...","Satisfied,Charging is really fast,Value for mo...",Looks durable Charging is fine tooNo complains...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Wayona-Braided-WN3LG1-Sy...
1,B098NS6PVG,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,Computers&Accessories|Accessories&Peripherals|...,₹199,₹349,43%,4.0,"43,994","Compatible with all Type C enabled devices, be...","AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBX...","ArdKn,Nirbhay kumar,Sagar Viswanathan,Asp,Plac...","RGIQEG07R9HS2,R1SMWZQ86XIN8U,R2J3Y1WL29GWDE,RY...","A Good Braided Cable for Your Type C Device,Go...",I ordered this cable to connect my phone to An...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Ambrane-Unbreakable-Char...
2,B096MSW6CT,Sounce Fast Phone Charging Cable & Data Sync U...,Computers&Accessories|Accessories&Peripherals|...,₹199,"₹1,899",90%,3.9,"7,928",【 Fast Charger& Data Sync】-With built-in safet...,"AGU3BBQ2V2DDAMOAKGFAWDDQ6QHA,AESFLDV2PT363T2AQ...","Kunal,Himanshu,viswanath,sai niharka,saqib mal...","R3J3EQQ9TZI5ZJ,R3E7WBGK7ID0KV,RWU79XKQ6I1QF,R2...","Good speed for earlier versions,Good Product,W...","Not quite durable and sturdy,https://m.media-a...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Sounce-iPhone-Charging-C...
3,B08HDJ86NZ,boAt Deuce USB 300 2 in 1 Type-C & Micro USB S...,Computers&Accessories|Accessories&Peripherals|...,₹329,₹699,53%,4.2,"94,363",The boAt Deuce USB 300 2 in 1 cable is compati...,"AEWAZDZZJLQUYVOVGBEUKSLXHQ5A,AG5HTSFRRE6NL3M5S...","Omkar dhale,JD,HEMALATHA,Ajwadh a.,amar singh ...","R3EEUZKKK9J36I,R3HJVYCLYOY554,REDECAZ7AMPQC,R1...","Good product,Good one,Nice,Really nice product...","Good product,long wire,Charges good,Nice,I bou...",https://m.media-amazon.com/images/I/41V5FtEWPk...,https://www.amazon.in/Deuce-300-Resistant-Tang...
4,B08CF3B7N1,Portronics Konnect L 1.2M Fast Charging 3A 8 P...,Computers&Accessories|Accessories&Peripherals|...,₹154,₹399,61%,4.2,"16,905",[CHARGE & SYNC FUNCTION]- This cable comes wit...,"AE3Q6KSUK5P75D5HFYHCRAOLODSA,AFUGIFH5ZAFXRDSZH...","rahuls6099,Swasat Borah,Ajay Wadke,Pranali,RVK...","R1BP4L2HH9TFUP,R16PVJEXKV6QZS,R2UPDB81N66T4P,R...","As good as original,Decent,Good one for second...","Bought this instead of original apple, does th...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Portronics-Konnect-POR-1...

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1465 entries, 0 to 1464
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   product_id           1465 non-null   str
 1   product_name         1465 non-null   str
 2   category             1465 non-null   str
 3   discounted_price     1465 non-null   str
 4   actual_price         1465 non-null   str
 5   discount_percentage  1465 non-null   str
 6   rating               1465 non-null   str
 7   rating_count         1463 non-null   str
 8   about_product        1465 non-null   str
 9   user_id              1465 non-null   str
 10  user_name            1465 non-null   str
 11  review_id            1465 non-null   str
 12  review_title         1465 non-null   str
 13  review_content       1465 non-null   str
 14  img_link             1465 non-null   str
 15  product_link         1465 non-null   str
dtypes: str(16)
memory usage: 4.7 MB

### Selecting Required Columns

In [4]:
df = df[
     [
        "product_id",
        "product_name",
        "category",
        "discounted_price",
        "actual_price",
        "discount_percentage",
        "rating",
        "rating_count",
        "user_id",
        "review_id"
    ]
]

In [5]:
df.columns.values

<ArrowStringArray>
[         'product_id',        'product_name',            'category',
    'discounted_price',        'actual_price', 'discount_percentage',
              'rating',        'rating_count',             'user_id',
           'review_id']
Length: 10, dtype: str

In [6]:
#col_names = ['Product_id', 'Product_name', 'Category', 'Discounted_price', 'Actual_price', 'Discount_percentage', 'Rating', 'Rating_count', 'User_id', 'Review_id']

In [7]:
df.head()

,product_id,product_name,category,discounted_price,actual_price,discount_percentage,rating,rating_count,user_id,review_id
0,B07JW9H4J1,Wayona Nylon Braided USB to Lightning Fast Cha...,Computers&Accessories|Accessories&Peripherals|...,₹399,"₹1,099",64%,4.2,"24,269","AG3D6O4STAQKAY2UVGEUV46KN35Q,AHMY5CWJMMK5BJRBB...","R3HXWT0LRP0NMF,R2AJM3LFTLZHFO,R6AQJGUP6P86,R1K..."
1,B098NS6PVG,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,Computers&Accessories|Accessories&Peripherals|...,₹199,₹349,43%,4.0,"43,994","AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBX...","RGIQEG07R9HS2,R1SMWZQ86XIN8U,R2J3Y1WL29GWDE,RY..."
2,B096MSW6CT,Sounce Fast Phone Charging Cable & Data Sync U...,Computers&Accessories|Accessories&Peripherals|...,₹199,"₹1,899",90%,3.9,"7,928","AGU3BBQ2V2DDAMOAKGFAWDDQ6QHA,AESFLDV2PT363T2AQ...","R3J3EQQ9TZI5ZJ,R3E7WBGK7ID0KV,RWU79XKQ6I1QF,R2..."
3,B08HDJ86NZ,boAt Deuce USB 300 2 in 1 Type-C & Micro USB S...,Computers&Accessories|Accessories&Peripherals|...,₹329,₹699,53%,4.2,"94,363","AEWAZDZZJLQUYVOVGBEUKSLXHQ5A,AG5HTSFRRE6NL3M5S...","R3EEUZKKK9J36I,R3HJVYCLYOY554,REDECAZ7AMPQC,R1..."
4,B08CF3B7N1,Portronics Konnect L 1.2M Fast Charging 3A 8 P...,Computers&Accessories|Accessories&Peripherals|...,₹154,₹399,61%,4.2,"16,905","AE3Q6KSUK5P75D5HFYHCRAOLODSA,AFUGIFH5ZAFXRDSZH...","R1BP4L2HH9TFUP,R16PVJEXKV6QZS,R2UPDB81N66T4P,R..."

### Clean "Discounted Price", "Actual Price" Column

In [8]:
df.columns.values

<ArrowStringArray>
[         'product_id',        'product_name',            'category',
    'discounted_price',        'actual_price', 'discount_percentage',
              'rating',        'rating_count',             'user_id',
           'review_id']
Length: 10, dtype: str

In [9]:
df["discounted_price"] = (
    df["discounted_price"]
    .str.replace("₹", "", regex=False)
    .str.replace(",", "", regex=False)
    .astype(float)
)

df['discounted_price'][0:4]

0    399.0
1    199.0
2    199.0
3    329.0
Name: discounted_price, dtype: float64

In [10]:
df["actual_price"] = (
    df["actual_price"]
    .str.replace("₹", "", regex=False)
    .str.replace(",", "", regex=False)
    .astype(float)
)

df['actual_price'][0:4]

0    1099.0
1     349.0
2    1899.0
3     699.0
Name: actual_price, dtype: float64

In [11]:
df["discount_percentage"] = (
    df["discount_percentage"]
    .str.replace("%", "", regex=False)
    .astype(float)
)
df["discount_percentage"][0:4]

0    64.0
1    43.0
2    90.0
3    53.0
Name: discount_percentage, dtype: float64

### Classify Rating into categories & working with rating count

In [12]:
df["rating"] = pd.to_numeric(df["rating"], errors="coerce")

df['rating_count'] = df['rating_count'].str.replace(',', '', regex=True)
df['rating_count']

0       24269
1       43994
2        7928
3       94363
4       16905
        ...
1460     1090
1461     4118
1462      468
1463     8031
1464     6987
Name: rating_count, Length: 1465, dtype: str

### Handling Missing Values

In [13]:
# Drop rows if core identity or pricing columns are missing
df = df.dropna(
    subset=[
        "product_id",
        "product_name",
        "discounted_price",
        "actual_price"
    ]
)

In [14]:
df['category'] = df['category'].fillna('UNKNOWN_CATEGORY')

df['discount_percentage'] = (
    (df['actual_price'] - df['discounted_price']) / df['actual_price'] * 100
)

df['rating'] = df.groupby('category')['rating']\
                 .transform(lambda x: x.fillna(x.mean()))

df['rating_count'] = df['rating_count'].fillna(0)

df['user_id'] = df['user_id'].fillna('UNKNOWN_USER')

df['review_id'] = df['review_id'].fillna(0)

In [15]:
df.columns.values

<ArrowStringArray>
[         'product_id',        'product_name',            'category',
    'discounted_price',        'actual_price', 'discount_percentage',
              'rating',        'rating_count',             'user_id',
           'review_id']
Length: 10, dtype: str

In [16]:
df.head()

,product_id,product_name,category,discounted_price,actual_price,discount_percentage,rating,rating_count,user_id,review_id
0,B07JW9H4J1,Wayona Nylon Braided USB to Lightning Fast Cha...,Computers&Accessories|Accessories&Peripherals|...,399.0,1099.0,63.694268,4.2,24269,"AG3D6O4STAQKAY2UVGEUV46KN35Q,AHMY5CWJMMK5BJRBB...","R3HXWT0LRP0NMF,R2AJM3LFTLZHFO,R6AQJGUP6P86,R1K..."
1,B098NS6PVG,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,Computers&Accessories|Accessories&Peripherals|...,199.0,349.0,42.979943,4.0,43994,"AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBX...","RGIQEG07R9HS2,R1SMWZQ86XIN8U,R2J3Y1WL29GWDE,RY..."
2,B096MSW6CT,Sounce Fast Phone Charging Cable & Data Sync U...,Computers&Accessories|Accessories&Peripherals|...,199.0,1899.0,89.520800,3.9,7928,"AGU3BBQ2V2DDAMOAKGFAWDDQ6QHA,AESFLDV2PT363T2AQ...","R3J3EQQ9TZI5ZJ,R3E7WBGK7ID0KV,RWU79XKQ6I1QF,R2..."
3,B08HDJ86NZ,boAt Deuce USB 300 2 in 1 Type-C & Micro USB S...,Computers&Accessories|Accessories&Peripherals|...,329.0,699.0,52.932761,4.2,94363,"AEWAZDZZJLQUYVOVGBEUKSLXHQ5A,AG5HTSFRRE6NL3M5S...","R3EEUZKKK9J36I,R3HJVYCLYOY554,REDECAZ7AMPQC,R1..."
4,B08CF3B7N1,Portronics Konnect L 1.2M Fast Charging 3A 8 P...,Computers&Accessories|Accessories&Peripherals|...,154.0,399.0,61.403509,4.2,16905,"AE3Q6KSUK5P75D5HFYHCRAOLODSA,AFUGIFH5ZAFXRDSZH...","R1BP4L2HH9TFUP,R16PVJEXKV6QZS,R2UPDB81N66T4P,R..."

In [17]:
df.isnull().sum()

product_id             0
product_name           0
category               0
discounted_price       0
actual_price           0
discount_percentage    0
rating                 0
rating_count           0
user_id                0
review_id              0
dtype: int64

# Clean Data Checkpoint

In [18]:
clean_df = df.copy()
clean_df.head()

,product_id,product_name,category,discounted_price,actual_price,discount_percentage,rating,rating_count,user_id,review_id
0,B07JW9H4J1,Wayona Nylon Braided USB to Lightning Fast Cha...,Computers&Accessories|Accessories&Peripherals|...,399.0,1099.0,63.694268,4.2,24269,"AG3D6O4STAQKAY2UVGEUV46KN35Q,AHMY5CWJMMK5BJRBB...","R3HXWT0LRP0NMF,R2AJM3LFTLZHFO,R6AQJGUP6P86,R1K..."
1,B098NS6PVG,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,Computers&Accessories|Accessories&Peripherals|...,199.0,349.0,42.979943,4.0,43994,"AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBX...","RGIQEG07R9HS2,R1SMWZQ86XIN8U,R2J3Y1WL29GWDE,RY..."
2,B096MSW6CT,Sounce Fast Phone Charging Cable & Data Sync U...,Computers&Accessories|Accessories&Peripherals|...,199.0,1899.0,89.520800,3.9,7928,"AGU3BBQ2V2DDAMOAKGFAWDDQ6QHA,AESFLDV2PT363T2AQ...","R3J3EQQ9TZI5ZJ,R3E7WBGK7ID0KV,RWU79XKQ6I1QF,R2..."
3,B08HDJ86NZ,boAt Deuce USB 300 2 in 1 Type-C & Micro USB S...,Computers&Accessories|Accessories&Peripherals|...,329.0,699.0,52.932761,4.2,94363,"AEWAZDZZJLQUYVOVGBEUKSLXHQ5A,AG5HTSFRRE6NL3M5S...","R3EEUZKKK9J36I,R3HJVYCLYOY554,REDECAZ7AMPQC,R1..."
4,B08CF3B7N1,Portronics Konnect L 1.2M Fast Charging 3A 8 P...,Computers&Accessories|Accessories&Peripherals|...,154.0,399.0,61.403509,4.2,16905,"AE3Q6KSUK5P75D5HFYHCRAOLODSA,AFUGIFH5ZAFXRDSZH...","R1BP4L2HH9TFUP,R16PVJEXKV6QZS,R2UPDB81N66T4P,R..."

In [19]:
clean_df.to_excel("clean_amazon_df.xlsx",index=False)

In [20]:
clean_df

,product_id,product_name,category,discounted_price,actual_price,discount_percentage,rating,rating_count,user_id,review_id
0,B07JW9H4J1,Wayona Nylon Braided USB to Lightning Fast Cha...,Computers&Accessories|Accessories&Peripherals|...,399.0,1099.0,63.694268,4.2,24269,"AG3D6O4STAQKAY2UVGEUV46KN35Q,AHMY5CWJMMK5BJRBB...","R3HXWT0LRP0NMF,R2AJM3LFTLZHFO,R6AQJGUP6P86,R1K..."
1,B098NS6PVG,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,Computers&Accessories|Accessories&Peripherals|...,199.0,349.0,42.979943,4.0,43994,"AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBX...","RGIQEG07R9HS2,R1SMWZQ86XIN8U,R2J3Y1WL29GWDE,RY..."
2,B096MSW6CT,Sounce Fast Phone Charging Cable & Data Sync U...,Computers&Accessories|Accessories&Peripherals|...,199.0,1899.0,89.520800,3.9,7928,"AGU3BBQ2V2DDAMOAKGFAWDDQ6QHA,AESFLDV2PT363T2AQ...","R3J3EQQ9TZI5ZJ,R3E7WBGK7ID0KV,RWU79XKQ6I1QF,R2..."
3,B08HDJ86NZ,boAt Deuce USB 300 2 in 1 Type-C & Micro USB S...,Computers&Accessories|Accessories&Peripherals|...,329.0,699.0,52.932761,4.2,94363,"AEWAZDZZJLQUYVOVGBEUKSLXHQ5A,AG5HTSFRRE6NL3M5S...","R3EEUZKKK9J36I,R3HJVYCLYOY554,REDECAZ7AMPQC,R1..."
4,B08CF3B7N1,Portronics Konnect L 1.2M Fast Charging 3A 8 P...,Computers&Accessories|Accessories&Peripherals|...,154.0,399.0,61.403509,4.2,16905,"AE3Q6KSUK5P75D5HFYHCRAOLODSA,AFUGIFH5ZAFXRDSZH...","R1BP4L2HH9TFUP,R16PVJEXKV6QZS,R2UPDB81N66T4P,R..."
...,...,...,...,...,...,...,...,...,...,...
1460,B08L7J3T31,Noir Aqua - 5pcs PP Spun Filter + 1 Spanner | ...,Home&Kitchen|Kitchen&HomeAppliances|WaterPurif...,379.0,919.0,58.759521,4.0,1090,"AHITFY6AHALOFOHOZEOC6XBP4FEA,AFRABBODZJZQB6Z4U...","R3G3XFHPBFF0E8,R3C0BZCD32EIGW,R2EBVBCN9QPD9R,R..."
1461,B01M6453MB,Prestige Delight PRWO Electric Rice Cooker (1 ...,Home&Kitchen|Kitchen&HomeAppliances|SmallKitch...,2280.0,3045.0,25.123153,4.1,4118,"AFG5FM3NEMOL6BNFRV2NK5FNJCHQ,AGEINTRN6Z563RMLH...","R3DDL2UPKQ2CK9,R2SYYU1OATVIU5,R1VM993161IYRW,R..."
1462,B009P2LIL4,Bajaj Majesty RX10 2000 Watts Heat Convector R...,"Home&Kitchen|Heating,Cooling&AirQuality|RoomHe...",2219.0,3080.0,27.954545,3.6,468,"AGVPWCMAHYQWJOQKMUJN4DW3KM5Q,AF4Q3E66MY4SR7YQZ...","R1TLRJVW4STY5I,R2O455KRN493R1,R3Q5MVGBRIAS2G,R..."
1463,B00J5DYCCA,Havells Ventil Air DSP 230mm Exhaust Fan (Pist...,"Home&Kitchen|Heating,Cooling&AirQuality|Fans|E...",1399.0,1890.0,25.978836,4.0,8031,"AF2JQCLSCY3QJATWUNNHUSVUPNQQ,AFDMLUXC5LS5RXDJS...","R39Q2Y79MM9SWK,R3079BG1NIH6MB,R29A31ZELTZNJM,R..."
1464,B01486F4G6,Borosil Jumbo 1000-Watt Grill Sandwich Maker (...,Home&Kitchen|Kitchen&HomeAppliances|SmallKitch...,2863.0,3690.0,22.411924,4.3,6987,"AFGW5PT3R6ZAVQR4Y5MWVAKBZAYA,AG7QNJ2SCS5VS5VYY...","R20RBRZ0WEUJT9,ROKIFK9R2ISSE,R30EEG2FNJSN5I,R2..."

In [21]:
clean_df.shape

(1465, 10)

In [22]:
clean_df.columns.values

<ArrowStringArray>
[         'product_id',        'product_name',            'category',
    'discounted_price',        'actual_price', 'discount_percentage',
              'rating',        'rating_count',             'user_id',
           'review_id']
Length: 10, dtype: str

# SQL CHECKPOINT

In [23]:
import sqlite3

# Create SQLite database file
conn = sqlite3.connect("amazon_analysis.db")

# Load dataframe into SQLite
clean_df.to_sql(
    name="amazon_products",
    con=conn,
    if_exists="replace",
    index=False
)

print("Data loaded into SQLite successfully")

Data loaded into SQLite successfully

In [24]:
pd.read_sql("SELECT COUNT(*) FROM amazon_products", conn)

   COUNT(*)
0      1465

### View Data

In [25]:
pd.read_sql(
    "SELECT * FROM amazon_products LIMIT 6",
    conn
)

,product_id,product_name,category,discounted_price,actual_price,discount_percentage,rating,rating_count,user_id,review_id
0,B07JW9H4J1,Wayona Nylon Braided USB to Lightning Fast Cha...,Computers&Accessories|Accessories&Peripherals|...,399.0,1099.0,63.694268,4.2,24269,"AG3D6O4STAQKAY2UVGEUV46KN35Q,AHMY5CWJMMK5BJRBB...","R3HXWT0LRP0NMF,R2AJM3LFTLZHFO,R6AQJGUP6P86,R1K..."
1,B098NS6PVG,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,Computers&Accessories|Accessories&Peripherals|...,199.0,349.0,42.979943,4.0,43994,"AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBX...","RGIQEG07R9HS2,R1SMWZQ86XIN8U,R2J3Y1WL29GWDE,RY..."
2,B096MSW6CT,Sounce Fast Phone Charging Cable & Data Sync U...,Computers&Accessories|Accessories&Peripherals|...,199.0,1899.0,89.520800,3.9,7928,"AGU3BBQ2V2DDAMOAKGFAWDDQ6QHA,AESFLDV2PT363T2AQ...","R3J3EQQ9TZI5ZJ,R3E7WBGK7ID0KV,RWU79XKQ6I1QF,R2..."
3,B08HDJ86NZ,boAt Deuce USB 300 2 in 1 Type-C & Micro USB S...,Computers&Accessories|Accessories&Peripherals|...,329.0,699.0,52.932761,4.2,94363,"AEWAZDZZJLQUYVOVGBEUKSLXHQ5A,AG5HTSFRRE6NL3M5S...","R3EEUZKKK9J36I,R3HJVYCLYOY554,REDECAZ7AMPQC,R1..."
4,B08CF3B7N1,Portronics Konnect L 1.2M Fast Charging 3A 8 P...,Computers&Accessories|Accessories&Peripherals|...,154.0,399.0,61.403509,4.2,16905,"AE3Q6KSUK5P75D5HFYHCRAOLODSA,AFUGIFH5ZAFXRDSZH...","R1BP4L2HH9TFUP,R16PVJEXKV6QZS,R2UPDB81N66T4P,R..."
5,B08Y1TFSP6,pTron Solero TB301 3A Type-C Data and Fast Cha...,Computers&Accessories|Accessories&Peripherals|...,149.0,1000.0,85.100000,3.9,24871,"AEQ2YMXSZWEOHK2EHTNLOS56YTZQ,AGRVINWECNY7323CW...","R7S8ANNSDPR40,R3CLZFLHVJU26P,RFF7U7MPQFUGR,R1M..."

### Products per Category

In [26]:
pd.read_sql(
    """
    SELECT category, COUNT(*) AS product_count
    FROM amazon_products
    GROUP BY category
    ORDER BY product_count DESC
    """,
    conn
)

                                              category  product_count
0    Computers&Accessories|Accessories&Peripherals|...            233
1          Electronics|WearableTechnology|SmartWatches             76
2    Electronics|Mobiles&Accessories|Smartphones&Ba...             68
3    Electronics|HomeTheater,TV&Video|Televisions|S...             63
4    Electronics|Headphones,Earbuds&Accessories|Hea...             52
..                                                 ...            ...
206  Computers&Accessories|Accessories&Peripherals|...              1
207  Computers&Accessories|Accessories&Peripherals|...              1
208  Computers&Accessories|Accessories&Peripherals|...              1
209  Computers&Accessories|Accessories&Peripherals|...              1
210  Car&Motorbike|CarAccessories|InteriorAccessori...              1

[211 rows x 2 columns]

### Average Rating by Category

In [27]:
pd.read_sql(
    """
    SELECT category, ROUND(AVG(rating), 2) AS avg_rating
    FROM amazon_products
    GROUP BY category
    ORDER BY avg_rating DESC
    """,
    conn
)

                                              category  avg_rating
0                        Computers&Accessories|Tablets         4.6
1    OfficeProducts|OfficeElectronics|Calculators|B...         4.5
2            HomeImprovement|Electrical|CordManagement         4.5
3    Home&Kitchen|Kitchen&HomeAppliances|SmallKitch...         4.5
4    Home&Kitchen|Kitchen&HomeAppliances|Coffee,Tea...         4.5
..                                                 ...         ...
206  Computers&Accessories|Accessories&Peripherals|...         3.6
207  Electronics|HomeTheater,TV&Video|Accessories|3...         3.5
208  Computers&Accessories|Accessories&Peripherals|...         3.5
209  Computers&Accessories|Accessories&Peripherals|...         3.4
210  Home&Kitchen|Kitchen&HomeAppliances|Coffee,Tea...         3.3

[211 rows x 2 columns]

### Top 10 highest-rated products

In [28]:
pd.read_sql(
    """
    SELECT product_name, rating
    FROM amazon_products
    ORDER BY rating DESC
    LIMIT 10
    """,
    conn
)

                                        product_name  rating
0  Syncwire LTG to USB Cable for Fast Charging Co...     5.0
1  REDTECH USB-C to Lightning Cable 3.3FT, [Apple...     5.0
2  Amazon Basics Wireless Mouse | 2.4 GHz Connect...     5.0
3  Swiffer Instant Electric Water Heater Faucet T...     4.8
4  Oratech Coffee Frother electric, milk frother ...     4.8
5  Instant Pot Air Fryer, Vortex 2QT, Touch Contr...     4.8
6  Sony Bravia 164 cm (65 inches) 4K Ultra HD Sma...     4.7
7  Spigen EZ Fit Tempered Glass Screen Protector ...     4.7
8  FIGMENT Handheld Milk Frother Rechargeable, 3-...     4.7
9  Zuvexa USB Rechargeable Electric Foam Maker - ...     4.7

In [29]:
clean_df.columns.values

<ArrowStringArray>
[         'product_id',        'product_name',            'category',
    'discounted_price',        'actual_price', 'discount_percentage',
              'rating',        'rating_count',             'user_id',
           'review_id']
Length: 10, dtype: str

### Products with high discount but low rating

In [30]:
pd.read_sql(
    """
    SELECT product_name, discounted_price, actual_price, discount_percentage
    FROM amazon_products
    WHERE discount_percentage > 40
    ORDER BY discount_percentage DESC
    LIMIT 10
    """,
    conn
)

,product_name,discounted_price,actual_price,discount_percentage
0,"rts [2 Pack] Mini USB C Type C Adapter Plug, T...",294.0,4999.0,94.118824
1,"Fire-Boltt Ninja Call Pro Plus 1.83"" Smart Wat...",1799.0,19999.0,91.004550
2,"Fire-Boltt Ninja Call Pro Plus 1.83"" Smart Wat...",1799.0,19999.0,91.004550
3,"Fire-Boltt Ninja Call Pro Plus 1.83"" Smart Wat...",1799.0,19999.0,91.004550
4,"Fire-Boltt Ninja Call Pro Plus 1.83"" Smart Wat...",1799.0,19999.0,91.004550
5,"Fire-Boltt Ninja Call Pro Plus 1.83"" Smart Wat...",1799.0,19999.0,91.004550
6,Sounce Spiral Charger Cable Protector Data Cab...,99.0,999.0,90.090090
7,LAPSTER 12pcs Spiral Cable Protectors for Char...,99.0,999.0,90.090090
8,LAPSTER Spiral Charger Spiral Charger Cable Pr...,99.0,999.0,90.090090
9,Sounce Spiral Charger Cable Protector Data Cab...,99.0,999.0,90.090090

### Best Price Segment

In [31]:
pd.read_sql(
    """
    SELECT
        CASE
            WHEN discounted_price < 500 THEN 'Low'
            WHEN discounted_price BETWEEN 500 AND 2000 THEN 'Medium'
            ELSE 'High'
        END AS price_range,
        ROUND(AVG(rating), 2) AS avg_rating,
        COUNT(product_id) AS total_products
    FROM amazon_products
    GROUP BY price_range
    ORDER BY avg_rating DESC;
    """,
    conn
)

  price_range  avg_rating  total_products
0        High        4.14             362
1      Medium        4.09             527
2         Low        4.07             576

In [32]:
pd.read_sql(
    """
    SELECT
        category,
        ROUND(AVG(rating), 2) AS avg_rating,
        COUNT(product_id) AS total_products
    FROM amazon_products
    GROUP BY category
    HAVING avg_rating >= 4.2
    ORDER BY total_products DESC;
    """,
    conn
)

,category,avg_rating,total_products
0,"Electronics|HomeTheater,TV&Video|Televisions|S...",4.21,63
1,"Electronics|HomeTheater,TV&Video|Accessories|C...",4.25,24
2,Computers&Accessories|Accessories&Peripherals|...,4.29,24
3,Electronics|Accessories|MemoryCards|MicroSD,4.33,13
4,Home&Kitchen|Kitchen&HomeAppliances|SmallKitch...,4.29,11
...,...,...,...
87,Computers&Accessories|ExternalDevices&DataStor...,4.30,1
88,Computers&Accessories|Components|Memory,4.50,1
89,Computers&Accessories|Components|InternalHardD...,4.20,1
90,Computers&Accessories|Accessories&Peripherals|...,4.30,1
91,Computers&Accessories|Accessories&Peripherals|...,4.40,1

### Rating Distribution

In [33]:
pd.read_sql(
    """
    SELECT
        CASE
            WHEN rating >= 4.5 THEN 'Excellent'
            WHEN rating BETWEEN 4.0 AND 4.49 THEN 'Good'
            WHEN rating BETWEEN 3.0 AND 3.99 THEN 'Average'
            ELSE 'Poor'
        END AS rating_category,
        COUNT(product_id) AS product_count
    FROM amazon_products
    GROUP BY rating_category
    ORDER BY product_count DESC;
    """,
    conn
)

  rating_category  product_count
0            Good           1006
1         Average            349
2       Excellent            104
3            Poor              6

### Most Popular High-Rated Products

In [34]:
pd.read_sql(
    """
    SELECT
        product_name,
        category,
        rating,
        rating_count,
        discount_percentage
    FROM amazon_products
    WHERE rating >= 4.5
    ORDER BY rating_count DESC
    LIMIT 5;
    """,
    conn
)

,product_name,category,rating,rating_count,discount_percentage
0,Camel Oil Pastel with Reusable Plastic Box - 5...,Home&Kitchen|CraftMaterials|PaintingMaterials,4.5,9427,0.000000
1,Crucial BX500 240GB 3D NAND SATA 6.35 cm (2.5-...,Computers&Accessories|Components|InternalSolid...,4.5,92925,41.451613
2,Melbon VM-905 2000-Watt Room Heater (ISI Certi...,"Home&Kitchen|Heating,Cooling&AirQuality|RoomHe...",4.6,9,66.722241
3,Cuzor 12V Mini ups for WiFi Router | Power Bac...,Computers&Accessories|NetworkingDevices|Routers,4.5,8656,50.016672
4,Classmate Soft Cover 6 Subject Spiral Binding ...,OfficeProducts|OfficePaperProducts|Paper|Stati...,4.5,8618,1.875000

### Price Sensitivity Analysis

In [35]:
pd.read_sql(
    """
    SELECT
        CASE
            WHEN discounted_price < 500 THEN 'Low'
            WHEN discounted_price BETWEEN 500 AND 2000 THEN 'Medium'
            ELSE 'High'
        END AS price_range,
        ROUND(AVG(discounted_price), 2) AS avg_price,
        ROUND(AVG(rating), 2) AS avg_rating
    FROM amazon_products
    GROUP BY price_range
    ORDER BY avg_price;
    """,
    conn
)

  price_range  avg_price  avg_rating
0         Low     276.73        4.07
1      Medium    1140.05        4.09
2        High   10548.00        4.14

In [38]:
conn.close()
print('Connection Closed')

Connection Closed